package com.gp.domain.test;

// Generated 6 sept. 2014 23:48:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bareme generated by hbm2java
 */
@Entity
@Table(name = "bareme", catalog = "gp")
public class Bareme implements java.io.Serializable {

	private Integer baremeId;
	private Set<Societebareme> societebaremes = new HashSet<Societebareme>(0);

	public Bareme() {
	}

	public Bareme(Set<Societebareme> societebaremes) {
		this.societebaremes = societebaremes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "baremeID", unique = true, nullable = false)
	public Integer getBaremeId() {
		return this.baremeId;
	}

	public void setBaremeId(Integer baremeId) {
		this.baremeId = baremeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bareme")
	public Set<Societebareme> getSocietebaremes() {
		return this.societebaremes;
	}

	public void setSocietebaremes(Set<Societebareme> societebaremes) {
		this.societebaremes = societebaremes;
	}

}
