package com.gp.domain.test;

// Generated 6 sept. 2014 23:48:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Excercice generated by hbm2java
 */
@Entity
@Table(name = "excercice", catalog = "gp")
public class Excercice implements java.io.Serializable {

	private Integer excerciceId;
	private Societe societe;

	public Excercice() {
	}

	public Excercice(Societe societe) {
		this.societe = societe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "excerciceID", unique = true, nullable = false)
	public Integer getExcerciceId() {
		return this.excerciceId;
	}

	public void setExcerciceId(Integer excerciceId) {
		this.excerciceId = excerciceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "societeID")
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

}
