package com.gp.domain.test;

// Generated 6 sept. 2014 23:48:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Salarie generated by hbm2java
 */
@Entity
@Table(name = "salarie", catalog = "gp")
public class Salarie implements java.io.Serializable {

	private Integer salarieId;
	private Contrat contrat;
	private Etatcivile etatcivile;
	private Paie paie;
	private Poste poste;
	private Coordonneebancaire coordonneebancaire;
	private Immatriculation immatriculation;
	private Societe societe;
	private Set<Prime> primes = new HashSet<Prime>(0);
	private Set<Conge> conges = new HashSet<Conge>(0);
	private Set<Ordrevirement> ordrevirements = new HashSet<Ordrevirement>(0);
	private Set<Document> documents = new HashSet<Document>(0);

	public Salarie() {
	}

	public Salarie(Contrat contrat, Etatcivile etatcivile, Paie paie,
			Poste poste, Coordonneebancaire coordonneebancaire,
			Immatriculation immatriculation, Societe societe,
			Set<Prime> primes, Set<Conge> conges,
			Set<Ordrevirement> ordrevirements, Set<Document> documents) {
		this.contrat = contrat;
		this.etatcivile = etatcivile;
		this.paie = paie;
		this.poste = poste;
		this.coordonneebancaire = coordonneebancaire;
		this.immatriculation = immatriculation;
		this.societe = societe;
		this.primes = primes;
		this.conges = conges;
		this.ordrevirements = ordrevirements;
		this.documents = documents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "salarieID", unique = true, nullable = false)
	public Integer getSalarieId() {
		return this.salarieId;
	}

	public void setSalarieId(Integer salarieId) {
		this.salarieId = salarieId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contratID")
	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etatcivileID")
	public Etatcivile getEtatcivile() {
		return this.etatcivile;
	}

	public void setEtatcivile(Etatcivile etatcivile) {
		this.etatcivile = etatcivile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paieID")
	public Paie getPaie() {
		return this.paie;
	}

	public void setPaie(Paie paie) {
		this.paie = paie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "posteID")
	public Poste getPoste() {
		return this.poste;
	}

	public void setPoste(Poste poste) {
		this.poste = poste;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coordoneebancaireID")
	public Coordonneebancaire getCoordonneebancaire() {
		return this.coordonneebancaire;
	}

	public void setCoordonneebancaire(Coordonneebancaire coordonneebancaire) {
		this.coordonneebancaire = coordonneebancaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "immatriculationID")
	public Immatriculation getImmatriculation() {
		return this.immatriculation;
	}

	public void setImmatriculation(Immatriculation immatriculation) {
		this.immatriculation = immatriculation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "societeID")
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Prime> getPrimes() {
		return this.primes;
	}

	public void setPrimes(Set<Prime> primes) {
		this.primes = primes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Conge> getConges() {
		return this.conges;
	}

	public void setConges(Set<Conge> conges) {
		this.conges = conges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Ordrevirement> getOrdrevirements() {
		return this.ordrevirements;
	}

	public void setOrdrevirements(Set<Ordrevirement> ordrevirements) {
		this.ordrevirements = ordrevirements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salarie")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
