package com.gp.domain.test;

// Generated 6 sept. 2014 23:48:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Societe generated by hbm2java
 */
@Entity
@Table(name = "societe", catalog = "gp")
public class Societe implements java.io.Serializable {

	private Integer societeId;
	private String nom;
	private Set<Salarie> salaries = new HashSet<Salarie>(0);
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
	private Set<Excercice> excercices = new HashSet<Excercice>(0);
	private Set<Societebareme> societebaremes = new HashSet<Societebareme>(0);

	public Societe() {
	}

	public Societe(String nom) {
		this.nom = nom;
	}

	public Societe(String nom, Set<Salarie> salaries,
			Set<Utilisateur> utilisateurs, Set<Excercice> excercices,
			Set<Societebareme> societebaremes) {
		this.nom = nom;
		this.salaries = salaries;
		this.utilisateurs = utilisateurs;
		this.excercices = excercices;
		this.societebaremes = societebaremes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "societeID", unique = true, nullable = false)
	public Integer getSocieteId() {
		return this.societeId;
	}

	public void setSocieteId(Integer societeId) {
		this.societeId = societeId;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "societe")
	public Set<Salarie> getSalaries() {
		return this.salaries;
	}

	public void setSalaries(Set<Salarie> salaries) {
		this.salaries = salaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "societe")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "societe")
	public Set<Excercice> getExcercices() {
		return this.excercices;
	}

	public void setExcercices(Set<Excercice> excercices) {
		this.excercices = excercices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "societe")
	public Set<Societebareme> getSocietebaremes() {
		return this.societebaremes;
	}

	public void setSocietebaremes(Set<Societebareme> societebaremes) {
		this.societebaremes = societebaremes;
	}

}
