package com.gp.domain;

// Generated 13 oct. 2014 17:42:27 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bareme generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bareme", catalog = "gp")
public class Bareme implements java.io.Serializable {

	private Integer baremeId;
	private String version;
	private String nom;
	private String tranche;
	private Integer type;
	private Set<Tranche> tranches = new HashSet<Tranche>(0);
	private Set<Societebareme> societebaremes = new HashSet<Societebareme>(0);

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "Bareme :  \nNom : "+this.nom+"\ntranche: "+this.tranche+
				"\nType : "+this.type+"\nversion : "+this.version+"\n------------------------------\n";
	}
	public boolean estObligatoire(){
		if(this.type.equals(1)) return true;
		return true;
	}
	public Bareme() {
		this.version = "1.0.0";
	}

	public Bareme(String nom, String tranche, Integer type) {
		this.nom = nom;
		this.tranche = tranche;
		this.type = type;
	}

	public Bareme(String nom, String tranche, Integer type,
			Set<Tranche> tranches, Set<Societebareme> societebaremes) {
		this.nom = nom;
		this.tranche = tranche;
		this.type = type;
		this.tranches = tranches;
		this.societebaremes = societebaremes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "baremeID", unique = true, nullable = false)
	public Integer getBaremeId() {
		return this.baremeId;
	}

	public void setBaremeId(Integer baremeId) {
		this.baremeId = baremeId;
	}

	
	@Column(name = "version", nullable = false, length = 50)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "tranche", nullable = false)
	public String getTranche() {
		return this.tranche;
	}

	public void setTranche(String tranche) {
		this.tranche = tranche;
	}

	@Column(name = "type", nullable = false, length = 100)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bareme")
	public Set<Tranche> getTranches() {
		return this.tranches;
	}

	public void setTranches(Set<Tranche> tranches) {
		this.tranches = tranches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bareme")
	public Set<Societebareme> getSocietebaremes() {
		return this.societebaremes;
	}

	public void setSocietebaremes(Set<Societebareme> societebaremes) {
		this.societebaremes = societebaremes;
	}

}
