package com.gp.domain;

// Generated 19 sept. 2014 17:14:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exercice generated by hbm2java
 */
@Entity
@Table(name = "exercice", catalog = "gp")
public class Exercice implements java.io.Serializable {

	private Integer exerciceId;
	private Societe societe;
	private String intituleExercice;
	private Date dateDebut;
	private Date dateFin;

	public Exercice() {
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.societe.getIntituleSociete()+": "+this.intituleExercice+"\n"+
				"du : "+this.dateDebut+" au "+this.dateFin;
	}
	public Exercice(String intituleExercice, Date dateDebut, Date dateFin) {
		this.intituleExercice = intituleExercice;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	public Exercice(Societe societe, String intituleExercice, Date dateDebut,
			Date dateFin) {
		this.societe = societe;
		this.intituleExercice = intituleExercice;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "exerciceID", unique = true, nullable = false)
	public Integer getExerciceId() {
		return this.exerciceId;
	}

	public void setExerciceId(Integer exerciceId) {
		this.exerciceId = exerciceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "societeID")
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@Column(name = "intituleExercice", nullable = false)
	public String getIntituleExercice() {
		return this.intituleExercice;
	}

	public void setIntituleExercice(String intituleExercice) {
		this.intituleExercice = intituleExercice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDebut", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateFin", nullable = false, length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
