package com.gp.domain;

// Generated 14 sept. 2014 16:09:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ordrevirement generated by hbm2java
 */
@Entity
@Table(name = "ordrevirement", catalog = "gp")
public class Ordrevirement implements java.io.Serializable {

	private Integer ordrevirementId;
	private Avance avance;
	private Salarie salarie;
	private Pret pret;
	private Date dateordrevirement;
	private String motif;

	public Ordrevirement() {
	}

	public Ordrevirement(Salarie salarie) {
		this.salarie = salarie;
	}

	public Ordrevirement(Avance avance, Salarie salarie, Pret pret,
			Date dateordrevirement, String motif) {
		this.avance = avance;
		this.salarie = salarie;
		this.pret = pret;
		this.dateordrevirement = dateordrevirement;
		this.motif = motif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ordrevirementID", unique = true, nullable = false)
	public Integer getOrdrevirementId() {
		return this.ordrevirementId;
	}

	public void setOrdrevirementId(Integer ordrevirementId) {
		this.ordrevirementId = ordrevirementId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "avanceID")
	public Avance getAvance() {
		return this.avance;
	}

	public void setAvance(Avance avance) {
		this.avance = avance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salarieID", nullable = false)
	public Salarie getSalarie() {
		return this.salarie;
	}

	public void setSalarie(Salarie salarie) {
		this.salarie = salarie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pretID")
	public Pret getPret() {
		return this.pret;
	}

	public void setPret(Pret pret) {
		this.pret = pret;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateordrevirement", length = 10)
	public Date getDateordrevirement() {
		return this.dateordrevirement;
	}

	public void setDateordrevirement(Date dateordrevirement) {
		this.dateordrevirement = dateordrevirement;
	}

	@Column(name = "motif")
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

}
