package com.gp.domainnews;

// Generated 11 oct. 2014 11:17:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etatcivile generated by hbm2java
 */
@Entity
@Table(name = "etatcivile", catalog = "gp")
public class Etatcivile implements java.io.Serializable {

	private Integer etatcivileId;
	private String civilite;
	private String matricule;
	private String nom;
	private String prenom;
	private String situationfamiliale;
	private Set<Salarie> salaries = new HashSet<Salarie>(0);
	private Set<Enfant> enfants = new HashSet<Enfant>(0);

	public Etatcivile() {
	}

	public Etatcivile(String civilite, String matricule, String nom,
			String prenom, String situationfamiliale, Set<Salarie> salaries,
			Set<Enfant> enfants) {
		this.civilite = civilite;
		this.matricule = matricule;
		this.nom = nom;
		this.prenom = prenom;
		this.situationfamiliale = situationfamiliale;
		this.salaries = salaries;
		this.enfants = enfants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "etatcivileID", unique = true, nullable = false)
	public Integer getEtatcivileId() {
		return this.etatcivileId;
	}

	public void setEtatcivileId(Integer etatcivileId) {
		this.etatcivileId = etatcivileId;
	}

	@Column(name = "civilite")
	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	@Column(name = "matricule")
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "situationfamiliale")
	public String getSituationfamiliale() {
		return this.situationfamiliale;
	}

	public void setSituationfamiliale(String situationfamiliale) {
		this.situationfamiliale = situationfamiliale;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatcivile")
	public Set<Salarie> getSalaries() {
		return this.salaries;
	}

	public void setSalaries(Set<Salarie> salaries) {
		this.salaries = salaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatcivile")
	public Set<Enfant> getEnfants() {
		return this.enfants;
	}

	public void setEnfants(Set<Enfant> enfants) {
		this.enfants = enfants;
	}

}
