package com.gp.domainnews;

// Generated 11 oct. 2014 11:17:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TrancheId generated by hbm2java
 */
@Embeddable
public class TrancheId implements java.io.Serializable {

	private double debut;
	private double fin;
	private double taux;
	private double deduire;
	private int bareme;

	public TrancheId() {
	}

	public TrancheId(double debut, double fin, double taux, double deduire,
			int bareme) {
		this.debut = debut;
		this.fin = fin;
		this.taux = taux;
		this.deduire = deduire;
		this.bareme = bareme;
	}

	@Column(name = "debut", nullable = false, precision = 22, scale = 0)
	public double getDebut() {
		return this.debut;
	}

	public void setDebut(double debut) {
		this.debut = debut;
	}

	@Column(name = "fin", nullable = false, precision = 22, scale = 0)
	public double getFin() {
		return this.fin;
	}

	public void setFin(double fin) {
		this.fin = fin;
	}

	@Column(name = "taux", nullable = false, precision = 22, scale = 0)
	public double getTaux() {
		return this.taux;
	}

	public void setTaux(double taux) {
		this.taux = taux;
	}

	@Column(name = "deduire", nullable = false, precision = 22, scale = 0)
	public double getDeduire() {
		return this.deduire;
	}

	public void setDeduire(double deduire) {
		this.deduire = deduire;
	}

	@Column(name = "bareme", nullable = false)
	public int getBareme() {
		return this.bareme;
	}

	public void setBareme(int bareme) {
		this.bareme = bareme;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrancheId))
			return false;
		TrancheId castOther = (TrancheId) other;

		return (this.getDebut() == castOther.getDebut())
				&& (this.getFin() == castOther.getFin())
				&& (this.getTaux() == castOther.getTaux())
				&& (this.getDeduire() == castOther.getDeduire())
				&& (this.getBareme() == castOther.getBareme());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDebut();
		result = 37 * result + (int) this.getFin();
		result = 37 * result + (int) this.getTaux();
		result = 37 * result + (int) this.getDeduire();
		result = 37 * result + this.getBareme();
		return result;
	}

}
