package com.gp.domainnews;

// Generated 11 oct. 2014 11:17:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tranche generated by hbm2java
 */
@Entity
@Table(name = "tranche", catalog = "gp")
public class Tranche implements java.io.Serializable {

	private TrancheId id;
	private Bareme bareme;

	public Tranche() {
	}

	public Tranche(TrancheId id, Bareme bareme) {
		this.id = id;
		this.bareme = bareme;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "debut", column = @Column(name = "debut", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "fin", column = @Column(name = "fin", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "taux", column = @Column(name = "taux", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "deduire", column = @Column(name = "deduire", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "bareme", column = @Column(name = "bareme", nullable = false)) })
	public TrancheId getId() {
		return this.id;
	}

	public void setId(TrancheId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bareme", nullable = false, insertable = false, updatable = false)
	public Bareme getBareme() {
		return this.bareme;
	}

	public void setBareme(Bareme bareme) {
		this.bareme = bareme;
	}

}
